### ISSUE TITLE
js-yaml dependency needs updating (security advisory)

### ISSUE THREAD

**Issue by mopagemo** [burstable/node-beanstalkd-client#11]
The js-yaml dependency should be upgraded to at least 3.13.1 due to a code injection vulnerability: https://www.npmjs.com/advisories/813.

Currently it's set to 3.4.2.

**Comment by mickhansen** [comment]
Luckily, no user input is passed to js-yaml. Will update dep.

**Comment by mopagemo** [comment]
That was amazingly fast. Thanks!
