### ISSUE TITLE
Add more documentation

### ISSUE THREAD

**Issue by call-a3** [burstable/node-beanstalkd-client#2]
I'm really missing some documentation and/or examples of how to use this client. 
In particular, I have no idea how to implement a complete and resilient job lifecycle as described in the beanstalkd protocol. How do I catch and handle DEADLINE_SOON messages from the server? How will I know if the server timed out a reserved job?

Any examples would be much appreciated :)

**Comment by mickhansen** [comment]
Sorry for not seeing this issue at all @call-a3, as mentioned in the readme this is a low level client that doesn't handle beanstalkd lifecycle management, you want a more full featured worker like https://github.com/burstable/node-beanstalkd-worker
