### ISSUE TITLE
Not enought documentation

### ISSUE THREAD

**Issue by kirill-dev-pro** [burstable/node-beanstalkd-client#3]
Please add more documentation/examples to Readme file that will show all functions.

**Comment by mickhansen** [comment]
@Zmeu213 The beanstalkd protocol describes all commands, any particular commands you are unsure about?

**Comment by kirill-dev-pro** [comment]
Well, your module implements functions
```
.connect()
.use(tube)
```
but what about others? Do they called like in beanstalkd protocol or there is some difference?

**Comment by mickhansen** [comment]
@Zmeu213 All methods from the protocol are implemented like the readme says. Everything is like the protocol except `put` which takes a body arg rather than a size arg

**Comment by kirill-dev-pro** [comment]
Oh ok, i should better read redme. Didnt saw the part about camelCase functions names.
Im looking for code examples first. It will be more obvious if you provide readme with code example for each function.

**Comment by mickhansen** [comment]
PR is always welcome, but this is a lowlevel client and not really plug-n-play worker solution :)

**Comment by kirill-dev-pro** [comment]
Why not? Its fine enough to build custom workers

**Comment by mickhansen** [comment]
https://github.com/burstable/node-beanstalkd-worker adds a bit more to it

**Comment by kirill-dev-pro** [comment]
Cool. You could also add part how to `require()` it in node without `import`

**Comment by trexanhvn** [comment]
> Cool. You could also add part how to `require()` it in node without `import`.

Why I can't use `require()` instead of `import`. It's always inform an error like this:
```
const beanstalkdInstance = new Beanstalkd({
                             ^
TypeError: Beanstalkd is not a constructor
```

**Comment by mickhansen** [comment]
@trexanhvn Because of ES6 compilation, use `.default`. So `require('beanstalkd').default`
