### ISSUE TITLE
Watch after Reserve not working

### ISSUE THREAD

**Issue by apmcodes** [burstable/node-beanstalkd-client#8]
In the below code, first reserve command is run and then watch command after 2 secs, but watch command callback is never run.

Is watch not allowed after reserve, so is the reserve is hanging blocking the connection and no further command is run? Is this the way beanstalkd works or is this this client library ...  

```
const Beanstalkd = require('beanstalkd').default;

let client = new Beanstalkd('127.0.0.1', 11300);
client.connect().then(function (client) {
    console.log('going to reserve');
    client.reserve()
        .then(function (err, jobid, payload) {
            if (err) { console.log(err) }
            console.log(`Job Id ${jobid}`);
            console.log(`Job data ${payload.toString()}`);
            client.destroy(jobid, function (err) {
                if (err) { console.log(err) }
                console.log(`Job deleted ${jobid}`);
            });
        });
})

setTimeout(() => {
    console.log('going to watch')
    client.watch('low-volume')
        .then((tubecount) => {
            console.log(tubecount);
        })
        .catch(err => {
            console.log(err);
        })
}, 2000)

setTimeout(function () {
    console.log("Hello");
}, 3000);

```

Output
```
going to reserve
going to watch
Hello

```

**Comment by apmcodes** [comment]
Seems as beanstalkd reserve is blocking call,  other commands such as watch/ ignore are hanging. Is there way to watch while the client is still in reserve?

**Comment by mickhansen** [comment]
That's simply how the protocol works @apmcodes, you can't use reserve and watch on the same connection.

Each instance of this library handles a single connection, it's up to you to manage them or use a higher level library

**Comment by apmcodes** [comment]
Thank you for the clarification.
